export const siteConfig = {
  businessName: "HAULED OFF",
  tagline: "We take it. You're done.",
  trade: "Junk Removal",
  phone: "(413) 555-0199",
  phoneHref: "tel:4135550199",
  email: "info@hauledoff.com",
  address: {
    street: "1200 Main Street",
    city: "Springfield",
    state: "MA",
    zip: "01103",
    full: "1200 Main Street, Springfield, MA 01103",
  },
  serviceArea: "Springfield and the Pioneer Valley",
  serviceAreaExtended:
    "Springfield, Chicopee, Holyoke, Agawam, Westfield, Ludlow, Palmer, Wilbraham, Enfield CT, Southwick, Amherst, Northampton",
  serviceAreaCities: [
    "Springfield",
    "Chicopee",
    "Holyoke",
    "Agawam",
    "Westfield",
    "Ludlow",
    "Palmer",
    "Wilbraham",
    "Enfield, CT",
    "Southwick",
    "Amherst",
    "Northampton",
  ],
  license: "MA HIC #XXXXXX",
  insurance: "Fully Insured & Licensed",
  bbb: "",
  hours: {
    weekday: "Mon-Fri 6am-7pm",
    saturday: "Sat 7am-4pm",
    sunday: "Closed",
    short: "Mon-Sat 6am-7pm",
  },
  stats: {
    years: "06+",
    projects: "4.2K",
    satisfaction: "24",
    rating: "4.9",
    reviews: "300+",
    totalClients: "1,200+",
    townsCovered: "24",
  },
  founded: "2018",
  founder: "Mike Russo",
  primaryDomain: process.env.NEXT_PUBLIC_PRIMARY_DOMAIN || "",
  googleReviewLink: process.env.NEXT_PUBLIC_GOOGLE_REVIEW_LINK || "#",
  nav: [
    { label: "Services", href: "/services" },
    { label: "About", href: "/about" },
    { label: "Gallery", href: "/gallery" },
    { label: "Reviews", href: "/reviews" },
    { label: "Contact", href: "/contact" },
  ],
  footerServices: [
    { label: "Estate Cleanouts", href: "/services#estate-cleanouts" },
    { label: "Furniture Removal", href: "/services#furniture-removal" },
    { label: "Appliance Disposal", href: "/services#appliance-disposal" },
    { label: "Garage Clear-Outs", href: "/services#garage-clearouts" },
    { label: "Construction Debris", href: "/services#construction-debris" },
    { label: "Yard Cleanups", href: "/services#yard-cleanups" },
  ],
  footerCompany: [
    { label: "Services", href: "/services" },
    { label: "About Us", href: "/about" },
    { label: "Gallery", href: "/gallery" },
    { label: "Reviews", href: "/reviews" },
    { label: "Contact", href: "/contact" },
  ],
} as const;
